openapi: 3.0.0
info:
  contact: {}
  description: |+
    The base URL for this API is: https://api.leaseweb.com/invoices/v1/ This API provides an overview of all your Invoices

  license:
    name: Apache 2.0
    url: http://developer.leaseweb.com
  title: Invoices
  version: v1
  x-logo:
    altText: Leaseweb developer documentation
    backgroundColor: '#5484c6'
    href: https://developer.leaseweb.com
    url: https://developer.leaseweb.com/images/logo.png
servers:
- url: https://api.leaseweb.com/invoices/v1
security:
- X-LSW-Auth: []
tags:
- description: |
    The API uses standard HTTP status codes to indicate the success or failure of the API call. The response will be JSON. Most APIs use the following format:

    ```json
    {
        "errorCode": "APP00800",
        "errorMessage": "The connection with the DB cannot be established.",
        "correlationId": "550e8400-e29b-41d4-a716-446655440000",
        "userMessage": "Cannot handle your request at the moment. Please try again later.",
        "reference": "https://developer.leaseweb.com/errors/APP00800"
    }
    ```
  name: Errors
  x-traitTag: true
- description: |
    Authentication for the APIs is required. To authenticate your call, you will need to sent your API key as `X-LSW-Auth` header.

    You can generate API keys in the [Customer Portal](https://secure.leaseweb.com/api-client-management/).
  name: API Key Authentication
  x-traitTag: true
paths:
  /invoices:
    get:
      description: This endpoint will return an overview of all the invoices for the
        customer.
      operationId: getInvoices
      parameters:
      - description: Limit the number of results returned.
        example: 20
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: Return results starting from the given offset.
        example: 10
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
                invoices:
                - id: "00000001"
                  date: 2019-05-06T00:00:00+00:00
                  dueDate: 2019-05-30T00:00:00+00:00
                  taxAmount: 0
                  netAmount: 1756.21
                  total: 1756.21
                  openAmount: 1756.21
                  currency: EUR
                  isPartialPaymentAllowed: true
                  status: OVERDUE
                - id: "00000002"
                  date: 2019-05-06T00:00:00+00:00
                  dueDate: 2019-05-30T00:00:00+00:00
                  taxAmount: 0
                  netAmount: 34
                  total: 34
                  openAmount: 34
                  currency: EUR
                  isPartialPaymentAllowed: true
                  status: OPEN
                - id: "00000003"
                  date: 2019-04-06T00:00:00+00:00
                  dueDate: 2019-04-30T00:00:00+00:00
                  taxAmount: 0
                  netAmount: 14.37
                  total: 14.37
                  openAmount: 0
                  currency: EUR
                  isPartialPaymentAllowed: false
                  status: PAID
                _metadata:
                  limit: 10
                  offset: 0
                  totalCount: 3
              schema:
                $ref: '#/components/schemas/getInvoicesResult'
          description: Ok.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "503"
                errorMessage: The API is not available at the moment.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Service Unavailable.
      summary: List Invoices
      tags:
      - invoice
  /invoices/export/csv:
    get:
      description: This endpoint exports all invoices for the current customer as
        a CSV file.
      operationId: getInvoicesExportCsv
      parameters:
      - description: |
          Filter invoices starting from this date.
          - Format: YYYY-MM-DD
          - Example: 2025-01-01
        explode: true
        in: query
        name: dateFrom
        required: false
        schema:
          format: date
          type: string
        style: form
      - description: |
          Filter invoices starting up to this date.
          - Format: YYYY-MM-DD
          - Example: 2025-01-01
        explode: true
        in: query
        name: dateTo
        required: false
        schema:
          format: date
          type: string
        style: form
      responses:
        "200":
          content:
            text/csv:
              example: |
                Invoice number,Date (UTC),Status,Open amount,Total
                12341234,2025-09-30T12:00:00+00:00,PAID,0,120
                12341235,2025-10-01T08:30:00+00:00,OPEN,50.50,200.50
                12341236,2025-11-01T08:30:00+00:00,OPEN,10.99,220.99
              schema:
                $ref: '#/components/schemas/getInvoicesExportCsvResult'
          description: CSV file with invoices.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "503"
                errorMessage: The API is not available at the moment.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Service Unavailable.
      summary: Export Invoices (CSV)
      tags:
      - invoice
  /invoices/{Id}:
    get:
      description: Get Invoice will return a single invoice for the customer.
      operationId: getInvoice
      parameters:
      - description: Invoice Id
        explode: false
        in: path
        name: Id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                id: "00000001"
                date: 2019-05-06T00:00:00+00:00
                dueDate: 2019-05-30T00:00:00+00:00
                taxAmount: 0
                netAmount: 1756.21
                total: 1756.21
                openAmount: 1756.21
                currency: EUR
                isPartialPaymentAllowed: true
                status: OPEN
                credits:
                - id: "00001211"
                  date: 2025-07-09T00:00:00+00:00
                  taxAmount: 1.5
                  netAmount: 13.5
                  total: 15
                lineItems:
                - product: Rackspace
                  unitAmount: 151.5
                  totalAmount: 151.5
                  fromDate: 2023-02-01T00:00:00
                  toDate: 2023-02-28T00:00:00Z
                  equipmentId: "1234"
                  contractId: "12345678"
                  quantity: 1
              schema:
                $ref: '#/components/schemas/getInvoiceResult'
          description: Ok.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "404":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "404"
                errorMessage: Resource not found
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Found.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "503"
                errorMessage: The API is not available at the moment.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Service Unavailable.
      summary: Inspect a invoice
      tags:
      - invoice
  /invoices/{Id}/pdf:
    get:
      description: This endpoint will return a PDF of a single invoice for the customer.
      operationId: getInvoicePdf
      parameters:
      - description: Invoice Id
        explode: false
        in: path
        name: Id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/pdf:
              example: (binary PDF content omitted)
              schema:
                $ref: '#/components/schemas/getInvoicePdfResult'
          description: Successful file download (PDF)
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "404":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "404"
                errorMessage: Resource not found
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Found.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "503"
                errorMessage: The API is not available at the moment.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Service Unavailable.
      summary: Get Invoice PDF
      tags:
      - invoice
  /proforma:
    get:
      description: This endpoint will return an overview of contract items that will
        be invoiced as of the 1st of the upcoming month.
      operationId: getProforma
      responses:
        "200":
          content:
            application/json:
              example:
                proformaDate: "020-06-01T00: 00: 00+00: 00"
                total: 352.55
                subTotal: 300.04
                vatAmount: 52.51
                currency: EUR
                contractItems:
                - contractId: "50000103"
                  equipmentId: "26430"
                  startDate: 2020-01-01T00:00:00+00:00
                  endDate: 2021-01-01T00:00:00+00:00
                  poNumber: "40002154000110"
                  product: Backup
                  reference: this is a reference
                  price: 150.05
                  currency: EUR
                - contractId: "50000103"
                  equipmentId: "26430"
                  startDate: 2020-01-01T00:00:00+00:00
                  endDate: 2021-01-01T00:00:00+00:00
                  poNumber: "40002154000110"
                  product: Dedicated server
                  reference: his is a reference
                  price: 150.05
                  currency: EUR
                _metadata:
                  limit: 10
                  offset: 0
                  totalCount: 2
              schema:
                $ref: '#/components/schemas/getProformaResult'
          description: Ok.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "404":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "404"
                errorMessage: Resource not found
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Found.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "503"
                errorMessage: The API is not available at the moment.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Service Unavailable.
      summary: Pro Forma
      tags:
      - invoice
components:
  parameters:
    limit:
      description: Limit the number of results returned.
      example: 20
      explode: true
      in: query
      name: limit
      required: false
      schema:
        type: integer
      style: form
    offset:
      description: Return results starting from the given offset.
      example: 10
      explode: true
      in: query
      name: offset
      required: false
      schema:
        type: integer
      style: form
    DateFrom:
      description: |
        Filter invoices starting from this date.
        - Format: YYYY-MM-DD
        - Example: 2025-01-01
      explode: true
      in: query
      name: dateFrom
      required: false
      schema:
        format: date
        type: string
      style: form
    DateTo:
      description: |
        Filter invoices starting up to this date.
        - Format: YYYY-MM-DD
        - Example: 2025-01-01
      explode: true
      in: query
      name: dateTo
      required: false
      schema:
        format: date
        type: string
      style: form
    Id:
      description: Invoice Id
      explode: false
      in: path
      name: Id
      required: true
      schema:
        type: string
      style: simple
  responses:
    "401":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "401"
            errorMessage: You are not authorized to view this resource.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Not Authorized.
    "403":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "403"
            errorMessage: Access to the requested resource is forbidden.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Forbidden.
    "404":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "404"
            errorMessage: Resource not found
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Not Found.
    "500":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "500"
            errorMessage: '''The API could not handle your request at this time.'
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Internal Server Error.
    "503":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "503"
            errorMessage: The API is not available at the moment.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Service Unavailable.
  schemas:
    _metadata:
      description: Metadata about the collection
      example:
        offset: 0
        limit: 5
        totalCount: 2
      properties:
        totalCount:
          description: Total amount of elements in this collection
          example: 2
          minimum: 0
          type: integer
        offset:
          default: 0
          description: The offset used to generate this response
          example: 0
          minimum: 0
          type: integer
        limit:
          default: 5
          description: The limit used to generate this response
          example: 5
          minimum: 0
          type: integer
      required:
      - limit
      - offset
      - totalCount
      title: metadata
      type: object
    getInvoicesResult:
      example:
        invoices:
        - date: date
          total: 1.4658129
          netAmount: 6.0274563
          dueDate: dueDate
          isPartialPaymentAllowed: true
          currency: EUR
          id: id
          taxAmount: 0.8008282
          openAmount: 5.962134
          status: OPEN
        - date: date
          total: 1.4658129
          netAmount: 6.0274563
          dueDate: dueDate
          isPartialPaymentAllowed: true
          currency: EUR
          id: id
          taxAmount: 0.8008282
          openAmount: 5.962134
          status: OPEN
        _metadata:
          offset: 0
          limit: 5
          totalCount: 2
      properties:
        invoices:
          description: Array of Invoices
          items:
            $ref: '#/components/schemas/invoice'
          type: array
        _metadata:
          $ref: '#/components/schemas/_metadata'
      type: object
    errorResult:
      example:
        errorMessage: errorMessage
        errorCode: errorCode
        correlationId: correlationId
        errorDetails:
          key:
          - errorDetails
          - errorDetails
      properties:
        correlationId:
          description: The correlation ID of the current request.
          type: string
        errorCode:
          description: The error code.
          type: string
        errorMessage:
          description: A human friendly description of the error.
          type: string
        errorDetails:
          additionalProperties:
            items:
              type: string
            type: array
          title: errorDetails
          type: object
      type: object
    getInvoicesExportCsvResult:
      description: |
        CSV file containing invoice data with the following columns:
        - Invoice number
        - Date (UTC)
        - Status
        - Open amount
        - Total
      format: binary
      type: string
    getInvoiceResult:
      example:
        date: 2019-05-06T00:00:00+00:00
        lineItems:
        - fromDate: fromDate
          totalAmount: 2.302136
          product: product
          quantity: 7
          toDate: toDate
          contractId: contractId
          unitAmount: 5.637377
          equipmentId: equipmentId
        - fromDate: fromDate
          totalAmount: 2.302136
          product: product
          quantity: 7
          toDate: toDate
          contractId: contractId
          unitAmount: 5.637377
          equipmentId: equipmentId
        total: 0.8008282
        netAmount: 0
        credits:
        - date: date
          total: 5.962134
          netAmount: 1.4658129
          id: id
          taxAmount: 6.0274563
        - date: date
          total: 5.962134
          netAmount: 1.4658129
          id: id
          taxAmount: 6.0274563
        dueDate: 2019-05-30T00:00:00+00:00
        isPartialPaymentAllowed: true
        currency: EUR
        id: "00000001"
        taxAmount: 0
        openAmount: 1756.21
        status: OPEN
      properties:
        id:
          description: The unique id of the invoice
          example: "00000001"
          type: string
        date:
          description: The date the invoice was issued
          example: 2019-05-06T00:00:00+00:00
          type: string
        dueDate:
          description: The date the invoice is due for payment
          example: 2019-05-30T00:00:00+00:00
          type: string
        taxAmount:
          description: The tax amount of the invoice
          example: 0
          format: float
          type: number
        total:
          description: The total amount of the invoice
          format: float
          type: number
        netAmount:
          description: The total amount of the invoice without the tax amount included
          example: 0
          format: float
          type: number
        openAmount:
          description: The open amount of the invoice
          example: 1756.21
          format: float
          type: number
        currency:
          description: The currency of the service price
          enum:
          - EUR
          - GBP
          - USD
          - SGD
          - AUD
          - HKD
          example: EUR
          type: string
        isPartialPaymentAllowed:
          description: The invoice can be paid partially
          example: true
          type: boolean
        status:
          description: The status of the invoice.
          enum:
          - OPEN
          - PAID
          - OVERDUE
          - CANCELLED
          type: string
        credits:
          description: Array of Credits
          items:
            $ref: '#/components/schemas/credit'
          type: array
        lineItems:
          description: All the line items attached to the invoice
          items:
            $ref: '#/components/schemas/lineItem'
          type: array
      type: object
    getInvoicePdfResult:
      format: binary
      type: string
    getProformaResult:
      example:
        contractItems:
        - reference: reference
          product: product
          endDate: endDate
          price: 0.8008282
          contractId: contractId
          currency: EUR
          equipmentId: equipmentId
          poNumber: poNumber
          startDate: startDate
        - reference: reference
          product: product
          endDate: endDate
          price: 0.8008282
          contractId: contractId
          currency: EUR
          equipmentId: equipmentId
          poNumber: poNumber
          startDate: startDate
        proformaDate: "2020-06-01T00: 00: 00+00: 00"
        total: 352.55
        currency: EUR
        subTotal: 300.04
        _metadata:
          offset: 0
          limit: 5
          totalCount: 2
        vatAmount: 52.51
      properties:
        proformaDate:
          description: The date of the next invoice on which this proforma is based
            on. (UTC)
          example: "2020-06-01T00: 00: 00+00: 00"
          type: string
        total:
          description: Total amount which will be invoiced the upcoming month.
          example: 352.55
          format: float
          type: number
        subTotal:
          description: Total amount without vat which will be invoiced the upcoming
            month.
          example: 300.04
          format: float
          type: number
        vatAmount:
          description: The total amount of tax.
          example: 52.51
          format: float
          type: number
        currency:
          description: The currency of the service price
          enum:
          - EUR
          - GBP
          - USD
          - SGD
          - AUD
          - HKD
          example: EUR
          type: string
        contractItems:
          description: Array of contract items
          items:
            $ref: '#/components/schemas/lineItem_1'
          type: array
        _metadata:
          $ref: '#/components/schemas/_metadata'
      type: object
    invoice:
      example:
        date: date
        total: 1.4658129
        netAmount: 6.0274563
        dueDate: dueDate
        isPartialPaymentAllowed: true
        currency: EUR
        id: id
        taxAmount: 0.8008282
        openAmount: 5.962134
        status: OPEN
      properties:
        id:
          description: The unique id of the invoice
          type: string
        date:
          description: The date the invoice was issued (UTC)
          type: string
        dueDate:
          description: The date the invoice is due for payment (UTC)
          type: string
        taxAmount:
          description: The amount of tax on the invoice
          format: float
          type: number
        netAmount:
          description: The total amount without the tax amount included
          format: float
          type: number
        total:
          description: The total amount of the invoice
          format: float
          type: number
        openAmount:
          description: The open amount of the invoice
          format: float
          type: number
        currency:
          description: The currency of the invoice.
          enum:
          - EUR
          - GBP
          - USD
          - SGD
          - AUD
          - HKD
          type: string
        isPartialPaymentAllowed:
          description: The invoice can be paid partially
          type: boolean
        status:
          description: The status of the invoice.
          enum:
          - OPEN
          - PAID
          - OVERDUE
          - CANCELLED
          type: string
      title: invoice
      type: object
    credit:
      example:
        date: date
        total: 5.962134
        netAmount: 1.4658129
        id: id
        taxAmount: 6.0274563
      properties:
        id:
          description: The unique id of the credit
          type: string
        date:
          description: The date the credit was issued (UTC)
          type: string
        taxAmount:
          description: The amount of tax on the credit
          format: float
          type: number
        netAmount:
          description: The total amount of the credit without the tax amount included
          format: float
          type: number
        total:
          description: The total amount of the credit
          format: float
          type: number
      title: credit
      type: object
    lineItem:
      example:
        fromDate: fromDate
        totalAmount: 2.302136
        product: product
        quantity: 7
        toDate: toDate
        contractId: contractId
        unitAmount: 5.637377
        equipmentId: equipmentId
      properties:
        product:
          description: A string to indicate what kind of product this is
          type: string
        unitAmount:
          description: The amount it cost for a single product unit.
          format: float
          type: number
        totalAmount:
          description: The total amount of the product
          format: float
          type: number
        fromDate:
          description: The product start date (UTC)
          type: string
        toDate:
          description: The product end date (UTC)
          type: string
        equipmentId:
          description: The id of the equipment
          type: string
        contractId:
          description: The id of the contract
          type: string
        quantity:
          description: The quantity of a product
          type: integer
      title: lineItem
      type: object
    lineItem_1:
      example:
        reference: reference
        product: product
        endDate: endDate
        price: 0.8008282
        contractId: contractId
        currency: EUR
        equipmentId: equipmentId
        poNumber: poNumber
        startDate: startDate
      properties:
        contractId:
          description: The unique id of the contract
          type: string
        equipmentId:
          description: The unique id of the equipment
          type: string
        startDate:
          description: The start date of the contract (UTC)
          type: string
        endDate:
          description: The end date of the contract (UTC)
          type: string
        poNumber:
          description: The purchase order number.
          type: string
        product:
          description: A string to indicate what kind of product this is
          type: string
        reference:
          description: The reference a customer gave to the service
          type: string
        price:
          description: The price of the contract item.
          format: float
          type: number
        currency:
          description: The currency of the service price
          enum:
          - EUR
          - GBP
          - USD
          - SGD
          - AUD
          - HKD
          example: EUR
          type: string
      title: lineItem
      type: object
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
    X-LSW-Auth:
      description: API key authentication by setting `X-LSW-Auth` header.
      in: header
      name: X-LSW-Auth
      type: apiKey
