openapi: 3.0.0
info:
  contact: {}
  description: This documents the rest api nse api provides.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: nse
  version: v2
  x-logo:
    url: https://developer.leaseweb.com/images/logo.png
    altText: Leaseweb developer documentation
    backgroundColor: '#5484c6'
    href: http://developer.leaseweb.com
servers:
- url: https://api.leaseweb.com/internal/nseapi/v2
security:
- ApiKeyAuth: []
tags:
- description: |
    The API uses standard HTTP status codes to indicate the success or failure of the API call. The response will be JSON. Most APIs use the following format:

    ```json
    {
        "errorCode": "APP00800",
        "errorMessage": "The connection with the DB cannot be established.",
        "correlationId": "550e8400-e29b-41d4-a716-446655440000",
        "userMessage": "Cannot handle your request at the moment. Please try again later.",
        "reference": "http://developer.leaseweb.com/errors/APP00800"
    }
    ```
  name: Errors
  x-traitTag: true
- description: |
    Authentication for the APIs is required. To authenticate your call, you will need to sent your API key as `X-LSW-Auth` header.

    You can generate API keys in the [Customer Portal](https://secure.leaseweb.com/api-client-management/).
  name: API Key Authentication
  x-traitTag: true
- description: |
    Network Interfaces
  name: Network Interfaces
- description: |
    Notification Settings
  name: Notification Settings
- description: |
    Servers
  name: Servers
paths:
  /servers/{serverId}/networkInterfaces:
    get:
      description: |
        List all network interfaces for this server, including their current status.
      operationId: getNetworkInterfaceList
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                _metadata:
                  limit: 10
                  offset: 0
                  totalCount: 1
                networkInterfaces:
                - linkSpeed: 100Mbps
                  operStatus: OPEN
                  status: OPEN
                  switchInterface: "33"
                  switchName: EVO-AA11-1
                  type: PUBLIC
              schema:
                $ref: '#/components/schemas/getNetworkInterfaceListResult'
          description: Ok.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: List network interfaces
      tags:
      - nse
  /servers/{serverId}/networkInterfaces/close:
    post:
      description: |
        Close all network interfaces for this server.
      operationId: closeNetworkInterfaces
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Close all network interfaces
      tags:
      - nse
  /servers/{serverId}/networkInterfaces/open:
    post:
      description: |
        Open all network interfaces of this server.
      operationId: openNetworkInterfaces
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Open all network interfaces
      tags:
      - nse
  /servers/{serverId}/networkInterfaces/{networkType}:
    get:
      description: |
        Show the network interface of the given type of this server, including its
        status.
      operationId: getNetworkInterface
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      - description: The network type
        explode: false
        in: path
        name: networkType
        required: true
        schema:
          $ref: '#/components/schemas/networkType'
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                linkSpeed: 100Mbps
                operStatus: OPEN
                status: OPEN
                switchInterface: "33"
                switchName: EVO-JV12-1
                type: PUBLIC
              schema:
                $ref: '#/components/schemas/networkInterface'
          description: Ok.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Show a network interface
      tags:
      - nse
  /servers/{serverId}/networkInterfaces/{networkType}/close:
    post:
      description: |
        Close the network interface of this type of this server.
      operationId: closeNetworkInterface
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      - description: The network type
        explode: false
        in: path
        name: networkType
        required: true
        schema:
          $ref: '#/components/schemas/networkType'
        style: simple
      responses:
        "204":
          description: No Content.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Close network interface
      tags:
      - nse
  /servers/{serverId}/networkInterfaces/{networkType}/open:
    post:
      description: |
        Open all network interfaces of the given type for this server.
      operationId: openNetworkInterface
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      - description: The network type
        explode: false
        in: path
        name: networkType
        required: true
        schema:
          $ref: '#/components/schemas/networkType'
        style: simple
      responses:
        "204":
          description: No Content.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Open network interface
      tags:
      - nse
  /servers/{serverId}/notificationSettings/ddos:
    get:
      description: |
        Show all DDoS Protection related notification settings for this server. These
        settings control if you want to be notified via email in case a DDoS was
        mitigated.
      operationId: getDdosNotificationSettingList
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                nulling: ENABLED
                scrubbing: DISABLED
              schema:
                $ref: '#/components/schemas/getDdosNotificationSettingResult'
          description: Ok.
        "400":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "400"
                errorDetails: {}
                errorMessage: The API could not interpret your request correctly.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Bad Request.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Inspect DDoS notification settings
      tags:
      - nse
    put:
      description: |
        Update your DDoS notification settings for this server.
      operationId: updateServerDdosNotificationSetting
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              nulling: DISABLED
              scrubbing: ENABLED
            schema:
              $ref: '#/components/schemas/updateDdosNotificationSettingOpts'
      responses:
        "204":
          description: No Content.
        "400":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "400"
                errorDetails: {}
                errorMessage: The API could not interpret your request correctly.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Bad Request.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Update DDoS notification settings
      tags:
      - nse
components:
  parameters:
    serverId:
      description: The ID of a server
      example: "12345"
      explode: false
      in: path
      name: serverId
      required: true
      schema:
        type: string
      style: simple
    networkType:
      description: The network type
      explode: false
      in: path
      name: networkType
      required: true
      schema:
        $ref: '#/components/schemas/networkType'
      style: simple
  responses:
    "204":
      description: No Content.
    "400":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "400"
            errorDetails: {}
            errorMessage: The API could not interpret your request correctly.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Bad Request.
    "401":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "401"
            errorMessage: You are not authorized to view this resource.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Not Authorized.
    "403":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "403"
            errorMessage: Access to the requested resource is forbidden.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Forbidden.
    "500":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "500"
            errorMessage: '''The API could not handle your request at this time.'
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Internal Server Error.
  schemas:
    _metadata:
      description: Metadata about the collection
      example:
        offset: 0
        limit: 5
        totalCount: 2
      properties:
        totalCount:
          description: Total amount of orders in this collection
          example: 2
          type: number
        offset:
          default: 0
          description: The offset used to generate this response
          example: 0
          type: number
        limit:
          default: 5
          description: The limit used to generate this response
          example: 5
          type: number
      title: metadata
      type: object
    networkInterface:
      example:
        switchInterface: switchInterface
        switchName: switchName
        operStatus: operStatus
        linkSpeed: linkSpeed
        type: type
        status: status
      properties:
        linkSpeed:
          description: The link speed
          type: string
        operStatus:
          description: The operational status
          type: string
        status:
          description: The administrative status
          type: string
        switchInterface:
          description: The switch port number
          type: string
        switchName:
          description: The switch name
          type: string
        type:
          description: The network type
          type: string
      type: object
    getNetworkInterfaceListResult:
      example:
        networkInterfaces:
        - switchInterface: switchInterface
          switchName: switchName
          operStatus: operStatus
          linkSpeed: linkSpeed
          type: type
          status: status
        - switchInterface: switchInterface
          switchName: switchName
          operStatus: operStatus
          linkSpeed: linkSpeed
          type: type
          status: status
        _metadata:
          offset: 0
          limit: 5
          totalCount: 2
      properties:
        _metadata:
          $ref: '#/components/schemas/_metadata'
        networkInterfaces:
          description: An array of network interfaces
          items:
            $ref: '#/components/schemas/networkInterface'
          type: array
      type: object
    errorResult:
      example:
        errorMessage: errorMessage
        errorCode: errorCode
        correlationId: correlationId
        errorDetails:
          key:
          - errorDetails
          - errorDetails
      properties:
        correlationId:
          description: The correlation ID of the current request.
          type: string
        errorCode:
          description: The error code.
          type: string
        errorMessage:
          description: A human friendly description of the error.
          type: string
        errorDetails:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
      type: object
    networkType:
      description: Type of network
      enum:
      - INTERNAL
      - PUBLIC
      - REMOTE_MANAGEMENT
      example: INTERNAL
      type: string
    getDdosNotificationSettingResult:
      example:
        nulling: nulling
        scrubbing: scrubbing
      properties:
        nulling:
          description: Email notifications for nulling events
          type: string
        scrubbing:
          description: Email notifications for scrubbing events
          type: string
      type: object
    updateDdosNotificationSettingOpts:
      properties:
        nulling:
          description: Enable or disable email notifications for nulling events
          enum:
          - ENABLED
          - DISABLED
          type: string
        scrubbing:
          description: Enable or disable email notifications for nulling events
          enum:
          - ENABLED
          - DISABLED
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      description: API key authentication by setting `X-LSW-Auth` header.
      in: header
      name: X-LSW-Auth
      type: apiKey
    BearerAuth:
      scheme: bearer
      type: http
