openapi: 3.0.0
info:
  contact: {}
  description: This documents the rest api bmsdb provides.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: bmsdb
  version: v2
  x-logo:
    url: https://developer.leaseweb.com/images/logo.png
    altText: Leaseweb developer documentation
    backgroundColor: '#5484c6'
    href: http://developer.leaseweb.com
servers:
- url: https://api.leaseweb.com/internal/bmsdb/v2
security:
- ApiKeyAuth: []
tags:
- description: |
    The API uses standard HTTP status codes to indicate the success or failure of the API call. The response will be JSON. Most APIs use the following format:

    ```json
    {
        "errorCode": "APP00800",
        "errorMessage": "The connection with the DB cannot be established.",
        "correlationId": "550e8400-e29b-41d4-a716-446655440000",
        "userMessage": "Cannot handle your request at the moment. Please try again later.",
        "reference": "http://developer.leaseweb.com/errors/APP00800"
    }
    ```
  name: Errors
  x-traitTag: true
- description: |
    Authentication for the APIs is required. To authenticate your call, you will need to sent your API key as `X-LSW-Auth` header.

    You can generate API keys in the [Customer Portal](https://secure.leaseweb.com/api-client-management/).
  name: API Key Authentication
  x-traitTag: true
- description: |
    Getting Started
  name: Getting Started
- description: |
    Servers
  name: Servers
paths:
  /servers/{serverId}/hardwareInfo:
    get:
      description: |
        This information is generated when running a hardware scan for your server. A
        hardware scan collects hardware information about your system.
      operationId: getServerHardware
      parameters:
      - description: The ID of a server
        example: "12345"
        explode: false
        in: path
        name: serverId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                id: "2378237"
                parserVersion: "3.6"
                result:
                  chassis:
                    description: Rack Mount Chassis
                    firmware:
                      date: 07/01/2013
                      description: BIOS
                      vendor: HP
                      version: J01
                    motherboard:
                      product: ""
                      serial: ""
                      vendor: ""
                    product: ProLiant DL120 G7 (647339-B21)
                    serial: CZ33109CHV
                    vendor: HP
                  cpu:
                  - capabilities:
                      cpufreq: CPU Frequency scaling
                      ht: HyperThreading
                      vmx: false
                      x86-64: 64bits extensions (x86-64)
                    description: Intel(R) Xeon(R) CPU E31230
                    hz: "2792640000"
                    serial_number: ""
                    settings:
                      cores: "4"
                      enabledcores: "4"
                      threads: "8"
                    slot: Proc 1
                    vendor: Intel Corp.
                  disks:
                  - description: ATA Disk
                    id: disk:0
                    product: Hitachi HDS72302
                    serial_number: MS77215W07S6SA
                    size: "2000398934016"
                    smartctl:
                      ata_version: ATA8-ACS T13/1699-D revision 4
                      attributes:
                        Power_On_Hours:
                          flag: 0x0012
                          id: '  9'
                          raw_value: "39832"
                          thresh: "000"
                          type: Old_age
                          updated: Always
                          value: "095"
                          when_failed: "-"
                          worst: "095"
                        Reallocated_Sector_Ct:
                          flag: 0x0033
                          id: '  5'
                          raw_value: "0"
                          thresh: "005"
                          type: Pre-fail
                          updated: Always
                          value: "100"
                          when_failed: "-"
                          worst: "100"
                      device_model: Hitachi HDS723020BLE640
                      execution_status: "0"
                      firmware_version: MX4OAAB0
                      is_sas: false
                      overall_health: PASSED
                      rpm: 7200 rpm
                      sata_version: "SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)"
                      sector_size: "512 bytes logical, 4096 bytes physical"
                      serial_number: MS77215W07S6SA
                      smart_error_log: No Errors Logged
                      smart_support:
                        available: true
                        enabled: true
                      smartctl_version: "6.2"
                      user_capacity: "2,000,398,934,016 bytes [2.00 TB]"
                    vendor: Hitachi
                  ipmi:
                    defgateway: 10.19.79.126
                    firmware: "1.88"
                    ipaddress: 10.19.79.67
                    ipsource: DHCP Address
                    macaddress: 28:92:4a:33:48:e8
                    subnetmask: 255.255.255.192
                    vendor: Hewlett-Packard
                  memory:
                  - clock_hz: "1333000000"
                    description: DIMM DDR3 Synchronous 1333 MHz (0.8 ns)
                    id: memory/bank:0
                    serial_number: 8369AF58
                    size_bytes: "4294967296"
                  - clock_hz: "1333000000"
                    description: DIMM DDR3 Synchronous 1333 MHz (0.8 ns)
                    id: memory/bank:1
                    serial_number: 8369B174
                    size_bytes: "4294967296"
                  network:
                  - capabilities:
                      autonegotiation: Auto-negotiation
                      bus_master: bus mastering
                      cap_list: PCI capabilities listing
                      ethernet: ""
                      link_speeds:
                        "1000bt-fd": 1Gbit/s (full duplex)
                        "100bt": 100Mbit/s
                        "100bt-fd": 100Mbit/s (full duplex)
                        "10bt": 10Mbit/s
                        "10bt-fd": 10Mbit/s (full duplex)
                      msi: Message Signalled Interrupts
                      msix: MSI-X
                      pciexpress: PCI Express
                      physical: Physical interface
                      pm: Power Management
                      tp: twisted pair
                    lldp:
                      chassis:
                        description: "Juniper Networks, Inc. ex3300-48t Ethernet Switch,\
                          \ kernel JUNOS 15.1R5.5, Build date: 2016-11-25 16:02:59\
                          \ UTC Copyright (c) 1996-2016 Juniper Networks, Inc."
                        mac_address: 4c:16:fc:3a:84:c0
                        name: EVO-NS19-1
                      port:
                        auto_negotiation:
                          enabled: "yes"
                          supported: "yes"
                        description: ge-0/0/2.0
                      vlan:
                        id: "0"
                        label: VLAN
                        name: default
                    logical_name: eth0
                    mac_address: 28:92:4a:33:48:e6
                    product: 82574L Gigabit Network Connection
                    settings:
                      autonegotiation: "on"
                      broadcast: "yes"
                      driver: e1000e
                      driverversion: 3.2.6-k
                      duplex: full
                      firmware: 2.1-2
                      ip: 212.32.230.67
                      latency: "0"
                      link: "yes"
                      multicast: "yes"
                      port: twisted pair
                      speed: 1Gbit/s
                    vendor: Intel Corporation
                scannedAt: 2017-09-27T14:21:01Z
                serverId: "62264"
              schema:
                $ref: '#/components/schemas/getServerHardwareResult'
          description: Ok.
        "400":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "400"
                errorDetails: {}
                errorMessage: The API could not interpret your request correctly.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Bad Request.
        "401":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "401"
                errorMessage: You are not authorized to view this resource.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Not Authorized.
        "403":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
        "500":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "500"
                errorMessage: '''The API could not handle your request at this time.'
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Internal Server Error.
        "503":
          content:
            application/json:
              example:
                correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
                errorCode: "403"
                errorMessage: Access to the requested resource is forbidden.
              schema:
                $ref: '#/components/schemas/errorResult'
          description: Forbidden.
      summary: Show hardware information
      tags:
      - bmsdb
components:
  parameters:
    serverId:
      description: The ID of a server
      example: "12345"
      explode: false
      in: path
      name: serverId
      required: true
      schema:
        type: string
      style: simple
  responses:
    "400":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "400"
            errorDetails: {}
            errorMessage: The API could not interpret your request correctly.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Bad Request.
    "401":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "401"
            errorMessage: You are not authorized to view this resource.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Not Authorized.
    "403":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "403"
            errorMessage: Access to the requested resource is forbidden.
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Forbidden.
    "500":
      content:
        application/json:
          example:
            correlationId: 289346a1-3eaf-4da4-b707-62ef12eb08be
            errorCode: "500"
            errorMessage: '''The API could not handle your request at this time.'
          schema:
            $ref: '#/components/schemas/errorResult'
      description: Internal Server Error.
  schemas:
    vendor:
      example: HP
      type: string
    serialNumber:
      example: CZ33109CHV
      type: string
    diskId:
      example: disk
      type: string
    attribute:
      example:
        flag: flag
        raw_value: raw_value
        worst: worst
        id: id
        type: type
        thresh: thresh
        updated: updated
        value: value
        when_failed: when_failed
      properties:
        flag:
          type: string
        id:
          type: string
        raw_value:
          type: string
        thresh:
          type: string
        type:
          type: string
        updated:
          type: string
        value:
          type: string
        when_failed:
          type: string
        worst:
          type: string
      title: attribute
      type: object
    macAddress:
      description: Represents a MAC Address in the standard colon delimited format.
        Eg. `01:23:45:67:89:0A`
      example: 00:15:17:DB:63:01
      pattern: "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})|([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\\
        .[0-9a-fA-F]{4})$"
      type: string
    memoryId:
      example: memory/bank:0
      type: string
    scannedAt:
      description: "Timestamp of hardware scan, the ISO-8601 format"
      example: 2017-09-27T14:21:01Z
      format: date-time
      type: string
    serverId:
      example: "62264"
      type: string
    getServerHardwareResult:
      example:
        result:
          ipmi:
            ipaddress: ipaddress
            vendor: HP
            ipsource: ipsource
            macaddress: 00:15:17:DB:63:01
            defgateway: defgateway
            firmware: firmware
            subnetmask: subnetmask
          memory:
          - size_bytes: "4294967296"
            clock_hz: "1333000000"
            description: description
            serial_number: CZ33109CHV
            id: memory/bank:0
          - size_bytes: "4294967296"
            clock_hz: "1333000000"
            description: description
            serial_number: CZ33109CHV
            id: memory/bank:0
          disks:
          - product: product
            smartctl:
              device_model: device_model
              ata_version: ata_version
              smart_support:
                available: true
                enabled: true
              serial_number: CZ33109CHV
              firmware_version: firmware_version
              rpm: rpm
              user_capacity: user_capacity
              execution_status: execution_status
              attributes:
                Power_On_Hours:
                  flag: flag
                  raw_value: raw_value
                  worst: worst
                  id: id
                  type: type
                  thresh: thresh
                  updated: updated
                  value: value
                  when_failed: when_failed
                Reallocated_Sector_Ct:
                  flag: flag
                  raw_value: raw_value
                  worst: worst
                  id: id
                  type: type
                  thresh: thresh
                  updated: updated
                  value: value
                  when_failed: when_failed
              sata_version: sata_version
              sector_size: sector_size
              smart_error_log: smart_error_log
              smartctl_version: smartctl_version
              overall_health: overall_health
              is_sas: true
            size: size
            vendor: HP
            description: description
            serial_number: CZ33109CHV
            id: disk
          - product: product
            smartctl:
              device_model: device_model
              ata_version: ata_version
              smart_support:
                available: true
                enabled: true
              serial_number: CZ33109CHV
              firmware_version: firmware_version
              rpm: rpm
              user_capacity: user_capacity
              execution_status: execution_status
              attributes:
                Power_On_Hours:
                  flag: flag
                  raw_value: raw_value
                  worst: worst
                  id: id
                  type: type
                  thresh: thresh
                  updated: updated
                  value: value
                  when_failed: when_failed
                Reallocated_Sector_Ct:
                  flag: flag
                  raw_value: raw_value
                  worst: worst
                  id: id
                  type: type
                  thresh: thresh
                  updated: updated
                  value: value
                  when_failed: when_failed
              sata_version: sata_version
              sector_size: sector_size
              smart_error_log: smart_error_log
              smartctl_version: smartctl_version
              overall_health: overall_health
              is_sas: true
            size: size
            vendor: HP
            description: description
            serial_number: CZ33109CHV
            id: disk
          cpu:
          - settings:
              enabledcores: enabledcores
              cores: cores
              threads: threads
            hz: hz
            capabilities:
              vmx: true
              x86-64: x86-64
              cpufreq: cpufreq
              ht: ht
            vendor: HP
            description: description
            serial_number: CZ33109CHV
            slot: slot
          - settings:
              enabledcores: enabledcores
              cores: cores
              threads: threads
            hz: hz
            capabilities:
              vmx: true
              x86-64: x86-64
              cpufreq: cpufreq
              ht: ht
            vendor: HP
            description: description
            serial_number: CZ33109CHV
            slot: slot
          chassis:
            product: product
            serial: CZ33109CHV
            vendor: HP
            motherboard:
              product: product
              serial: CZ33109CHV
              vendor: HP
            description: description
            firmware:
              date: 2000-01-23
              vendor: HP
              description: description
              version: J01
          network:
          - settings:
              broadcast: "yes"
              driver: driver
              port: port
              ip: ip
              latency: latency
              link: "yes"
              duplex: full
              driverversion: driverversion
              firmware: firmware
              autonegotiation: "on"
              multicast: "yes"
              speed: 1Gbit/s
            logical_name: logical_name
            product: product
            capabilities:
              ethernet: ethernet
              msi: msi
              pciexpress: pciexpress
              link_speeds:
                "1000bt-fd": 1000bt-fd
                "10bt": 10bt
                "100bt": 100bt
                "10bt-fd": 10bt-fd
                "100bt-fd": 100bt-fd
              msix: msix
              cap_list: cap_list
              bus_master: bus_master
              physical: physical
              tp: tp
              pm: pm
              autonegotiation: autonegotiation
            mac_address: 00:15:17:DB:63:01
            vendor: HP
            lldp:
              vlan:
                name: name
                id: id
                label: label
              port:
                description: description
                auto_negotiation:
                  enabled: "yes"
                  supported: "yes"
              chassis:
                mac_address: 00:15:17:DB:63:01
                name: name
                description: description
          - settings:
              broadcast: "yes"
              driver: driver
              port: port
              ip: ip
              latency: latency
              link: "yes"
              duplex: full
              driverversion: driverversion
              firmware: firmware
              autonegotiation: "on"
              multicast: "yes"
              speed: 1Gbit/s
            logical_name: logical_name
            product: product
            capabilities:
              ethernet: ethernet
              msi: msi
              pciexpress: pciexpress
              link_speeds:
                "1000bt-fd": 1000bt-fd
                "10bt": 10bt
                "100bt": 100bt
                "10bt-fd": 10bt-fd
                "100bt-fd": 100bt-fd
              msix: msix
              cap_list: cap_list
              bus_master: bus_master
              physical: physical
              tp: tp
              pm: pm
              autonegotiation: autonegotiation
            mac_address: 00:15:17:DB:63:01
            vendor: HP
            lldp:
              vlan:
                name: name
                id: id
                label: label
              port:
                description: description
                auto_negotiation:
                  enabled: "yes"
                  supported: "yes"
              chassis:
                mac_address: 00:15:17:DB:63:01
                name: name
                description: description
        parserVersion: parserVersion
        scannedAt: 2017-09-27T14:21:01Z
        id: id
        serverId: "62264"
      properties:
        id:
          description: Id of this hardware scan result
          type: string
        parserVersion:
          description: Version of the parser used for this hardware info
          type: string
        result:
          $ref: '#/components/schemas/result'
        scannedAt:
          description: "Timestamp of hardware scan, the ISO-8601 format"
          example: 2017-09-27T14:21:01Z
          format: date-time
          type: string
        serverId:
          example: "62264"
          type: string
      type: object
    errorResult:
      example:
        errorMessage: errorMessage
        errorCode: errorCode
        correlationId: correlationId
        errorDetails:
          key:
          - errorDetails
          - errorDetails
      properties:
        correlationId:
          description: The correlation ID of the current request.
          type: string
        errorCode:
          description: The error code.
          type: string
        errorMessage:
          description: A human friendly description of the error.
          type: string
        errorDetails:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
      type: object
    firmware:
      example:
        date: 2000-01-23
        vendor: HP
        description: description
        version: J01
      properties:
        date:
          format: date
          type: string
        description:
          type: string
        vendor:
          example: HP
          type: string
        version:
          example: J01
          type: string
      title: firmware
      type: object
    motherboard:
      example:
        product: product
        serial: CZ33109CHV
        vendor: HP
      properties:
        product:
          type: string
        serial:
          example: CZ33109CHV
          type: string
        vendor:
          example: HP
          type: string
      title: motherboard
      type: object
    chassis:
      example:
        product: product
        serial: CZ33109CHV
        vendor: HP
        motherboard:
          product: product
          serial: CZ33109CHV
          vendor: HP
        description: description
        firmware:
          date: 2000-01-23
          vendor: HP
          description: description
          version: J01
      properties:
        description:
          type: string
        firmware:
          $ref: '#/components/schemas/firmware'
        motherboard:
          $ref: '#/components/schemas/motherboard'
        product:
          type: string
        serial:
          example: CZ33109CHV
          type: string
        vendor:
          example: HP
          type: string
      title: chassis
      type: object
    cpuCapabilities:
      example:
        vmx: true
        x86-64: x86-64
        cpufreq: cpufreq
        ht: ht
      properties:
        cpufreq:
          type: string
        ht:
          type: string
        vmx:
          type: boolean
        x86-64:
          type: string
      title: cpuCapabilities
      type: object
    cpuSettings:
      example:
        enabledcores: enabledcores
        cores: cores
        threads: threads
      properties:
        cores:
          type: string
        enabledcores:
          type: string
        threads:
          type: string
      title: cpuSettings
      type: object
    cpu:
      example:
        settings:
          enabledcores: enabledcores
          cores: cores
          threads: threads
        hz: hz
        capabilities:
          vmx: true
          x86-64: x86-64
          cpufreq: cpufreq
          ht: ht
        vendor: HP
        description: description
        serial_number: CZ33109CHV
        slot: slot
      properties:
        capabilities:
          $ref: '#/components/schemas/cpuCapabilities'
        description:
          type: string
        hz:
          type: string
        serial_number:
          example: CZ33109CHV
          type: string
        settings:
          $ref: '#/components/schemas/cpuSettings'
        slot:
          type: string
        vendor:
          example: HP
          type: string
      title: cpu
    attributes:
      example:
        Power_On_Hours:
          flag: flag
          raw_value: raw_value
          worst: worst
          id: id
          type: type
          thresh: thresh
          updated: updated
          value: value
          when_failed: when_failed
        Reallocated_Sector_Ct:
          flag: flag
          raw_value: raw_value
          worst: worst
          id: id
          type: type
          thresh: thresh
          updated: updated
          value: value
          when_failed: when_failed
      properties:
        Power_On_Hours:
          $ref: '#/components/schemas/attribute'
        Reallocated_Sector_Ct:
          $ref: '#/components/schemas/attribute'
      title: attributes
      type: object
    smartSupport:
      example:
        available: true
        enabled: true
      properties:
        available:
          type: boolean
        enabled:
          type: boolean
      title: smartSupport
      type: object
    smartctl:
      example:
        device_model: device_model
        ata_version: ata_version
        smart_support:
          available: true
          enabled: true
        serial_number: CZ33109CHV
        firmware_version: firmware_version
        rpm: rpm
        user_capacity: user_capacity
        execution_status: execution_status
        attributes:
          Power_On_Hours:
            flag: flag
            raw_value: raw_value
            worst: worst
            id: id
            type: type
            thresh: thresh
            updated: updated
            value: value
            when_failed: when_failed
          Reallocated_Sector_Ct:
            flag: flag
            raw_value: raw_value
            worst: worst
            id: id
            type: type
            thresh: thresh
            updated: updated
            value: value
            when_failed: when_failed
        sata_version: sata_version
        sector_size: sector_size
        smart_error_log: smart_error_log
        smartctl_version: smartctl_version
        overall_health: overall_health
        is_sas: true
      properties:
        ata_version:
          type: string
        attributes:
          $ref: '#/components/schemas/attributes'
        device_model:
          type: string
        execution_status:
          type: string
        firmware_version:
          type: string
        is_sas:
          type: boolean
        overall_health:
          type: string
        rpm:
          type: string
        sata_version:
          type: string
        sector_size:
          type: string
        serial_number:
          example: CZ33109CHV
          type: string
        smart_error_log:
          type: string
        smart_support:
          $ref: '#/components/schemas/smartSupport'
        smartctl_version:
          type: string
        user_capacity:
          type: string
      title: smartctl
      type: object
    disk:
      example:
        product: product
        smartctl:
          device_model: device_model
          ata_version: ata_version
          smart_support:
            available: true
            enabled: true
          serial_number: CZ33109CHV
          firmware_version: firmware_version
          rpm: rpm
          user_capacity: user_capacity
          execution_status: execution_status
          attributes:
            Power_On_Hours:
              flag: flag
              raw_value: raw_value
              worst: worst
              id: id
              type: type
              thresh: thresh
              updated: updated
              value: value
              when_failed: when_failed
            Reallocated_Sector_Ct:
              flag: flag
              raw_value: raw_value
              worst: worst
              id: id
              type: type
              thresh: thresh
              updated: updated
              value: value
              when_failed: when_failed
          sata_version: sata_version
          sector_size: sector_size
          smart_error_log: smart_error_log
          smartctl_version: smartctl_version
          overall_health: overall_health
          is_sas: true
        size: size
        vendor: HP
        description: description
        serial_number: CZ33109CHV
        id: disk
      properties:
        description:
          type: string
        id:
          example: disk
          type: string
        product:
          type: string
        serial_number:
          example: CZ33109CHV
          type: string
        size:
          type: string
        smartctl:
          $ref: '#/components/schemas/smartctl'
        vendor:
          example: HP
          type: string
      title: disk
    ipmi:
      example:
        ipaddress: ipaddress
        vendor: HP
        ipsource: ipsource
        macaddress: 00:15:17:DB:63:01
        defgateway: defgateway
        firmware: firmware
        subnetmask: subnetmask
      properties:
        defgateway:
          format: ipv4
          type: string
        firmware:
          type: string
        ipaddress:
          format: ipv4
          type: string
        ipsource:
          type: string
        macaddress:
          description: Represents a MAC Address in the standard colon delimited format.
            Eg. `01:23:45:67:89:0A`
          example: 00:15:17:DB:63:01
          pattern: "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})|([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\\
            .[0-9a-fA-F]{4})$"
          type: string
        subnetmask:
          format: ipv4
          type: string
        vendor:
          example: HP
          type: string
      title: ipmi
      type: object
    memoryBank:
      example:
        size_bytes: "4294967296"
        clock_hz: "1333000000"
        description: description
        serial_number: CZ33109CHV
        id: memory/bank:0
      properties:
        description:
          type: string
        id:
          example: memory/bank:0
          type: string
        clock_hz:
          example: "1333000000"
          type: string
        serial_number:
          example: CZ33109CHV
          type: string
        size_bytes:
          example: "4294967296"
          type: string
      title: memoryBank
      type: object
    linkSpeeds:
      example:
        "1000bt-fd": 1000bt-fd
        "10bt": 10bt
        "100bt": 100bt
        "10bt-fd": 10bt-fd
        "100bt-fd": 100bt-fd
      properties:
        "1000bt-fd":
          type: string
        "100bt":
          type: string
        "100bt-fd":
          type: string
        "10bt":
          type: string
        "10bt-fd":
          type: string
      title: linkSpeeds
      type: object
    networkCapabilities:
      example:
        ethernet: ethernet
        msi: msi
        pciexpress: pciexpress
        link_speeds:
          "1000bt-fd": 1000bt-fd
          "10bt": 10bt
          "100bt": 100bt
          "10bt-fd": 10bt-fd
          "100bt-fd": 100bt-fd
        msix: msix
        cap_list: cap_list
        bus_master: bus_master
        physical: physical
        tp: tp
        pm: pm
        autonegotiation: autonegotiation
      properties:
        autonegotiation:
          type: string
        bus_master:
          type: string
        cap_list:
          type: string
        ethernet:
          type: string
        link_speeds:
          $ref: '#/components/schemas/linkSpeeds'
        msi:
          type: string
        msix:
          type: string
        pciexpress:
          type: string
        physical:
          type: string
        pm:
          type: string
        tp:
          type: string
      title: networkCapabilities
      type: object
    lldpChassis:
      example:
        mac_address: 00:15:17:DB:63:01
        name: name
        description: description
      properties:
        description:
          type: string
        mac_address:
          description: Represents a MAC Address in the standard colon delimited format.
            Eg. `01:23:45:67:89:0A`
          example: 00:15:17:DB:63:01
          pattern: "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})|([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\\
            .[0-9a-fA-F]{4})$"
          type: string
        name:
          type: string
      title: lldpChassis
      type: object
    autoNegotiation:
      example:
        enabled: "yes"
        supported: "yes"
      properties:
        enabled:
          enum:
          - "yes"
          - "no"
          type: string
        supported:
          enum:
          - "yes"
          - "no"
          type: string
      title: autoNegotiation
      type: object
    port:
      example:
        description: description
        auto_negotiation:
          enabled: "yes"
          supported: "yes"
      properties:
        auto_negotiation:
          $ref: '#/components/schemas/autoNegotiation'
        description:
          type: string
      title: port
      type: object
    vlan:
      example:
        name: name
        id: id
        label: label
      properties:
        id:
          type: string
        label:
          type: string
        name:
          type: string
      title: vlan
      type: object
    lldp:
      example:
        vlan:
          name: name
          id: id
          label: label
        port:
          description: description
          auto_negotiation:
            enabled: "yes"
            supported: "yes"
        chassis:
          mac_address: 00:15:17:DB:63:01
          name: name
          description: description
      properties:
        chassis:
          $ref: '#/components/schemas/lldpChassis'
        port:
          $ref: '#/components/schemas/port'
        vlan:
          $ref: '#/components/schemas/vlan'
      title: lldp
      type: object
    networkSettings:
      example:
        broadcast: "yes"
        driver: driver
        port: port
        ip: ip
        latency: latency
        link: "yes"
        duplex: full
        driverversion: driverversion
        firmware: firmware
        autonegotiation: "on"
        multicast: "yes"
        speed: 1Gbit/s
      properties:
        autonegotiation:
          enum:
          - "on"
          - "off"
          type: string
        broadcast:
          enum:
          - "yes"
          - "no"
          type: string
        driver:
          type: string
        driverversion:
          type: string
        duplex:
          example: full
          type: string
        firmware:
          type: string
        ip:
          format: ipv4
          type: string
        latency:
          type: string
        link:
          enum:
          - "yes"
          - "no"
          type: string
        multicast:
          enum:
          - "yes"
          - "no"
          type: string
        port:
          type: string
        speed:
          example: 1Gbit/s
          type: string
      title: networkSettings
      type: object
    network:
      example:
        settings:
          broadcast: "yes"
          driver: driver
          port: port
          ip: ip
          latency: latency
          link: "yes"
          duplex: full
          driverversion: driverversion
          firmware: firmware
          autonegotiation: "on"
          multicast: "yes"
          speed: 1Gbit/s
        logical_name: logical_name
        product: product
        capabilities:
          ethernet: ethernet
          msi: msi
          pciexpress: pciexpress
          link_speeds:
            "1000bt-fd": 1000bt-fd
            "10bt": 10bt
            "100bt": 100bt
            "10bt-fd": 10bt-fd
            "100bt-fd": 100bt-fd
          msix: msix
          cap_list: cap_list
          bus_master: bus_master
          physical: physical
          tp: tp
          pm: pm
          autonegotiation: autonegotiation
        mac_address: 00:15:17:DB:63:01
        vendor: HP
        lldp:
          vlan:
            name: name
            id: id
            label: label
          port:
            description: description
            auto_negotiation:
              enabled: "yes"
              supported: "yes"
          chassis:
            mac_address: 00:15:17:DB:63:01
            name: name
            description: description
      properties:
        capabilities:
          $ref: '#/components/schemas/networkCapabilities'
        lldp:
          $ref: '#/components/schemas/lldp'
        logical_name:
          type: string
        mac_address:
          description: Represents a MAC Address in the standard colon delimited format.
            Eg. `01:23:45:67:89:0A`
          example: 00:15:17:DB:63:01
          pattern: "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})|([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\\
            .[0-9a-fA-F]{4})$"
          type: string
        product:
          type: string
        settings:
          $ref: '#/components/schemas/networkSettings'
        vendor:
          example: HP
          type: string
      title: network
    result:
      description: "Hardware info e.g. chassis, cpu, memory and etc."
      example:
        ipmi:
          ipaddress: ipaddress
          vendor: HP
          ipsource: ipsource
          macaddress: 00:15:17:DB:63:01
          defgateway: defgateway
          firmware: firmware
          subnetmask: subnetmask
        memory:
        - size_bytes: "4294967296"
          clock_hz: "1333000000"
          description: description
          serial_number: CZ33109CHV
          id: memory/bank:0
        - size_bytes: "4294967296"
          clock_hz: "1333000000"
          description: description
          serial_number: CZ33109CHV
          id: memory/bank:0
        disks:
        - product: product
          smartctl:
            device_model: device_model
            ata_version: ata_version
            smart_support:
              available: true
              enabled: true
            serial_number: CZ33109CHV
            firmware_version: firmware_version
            rpm: rpm
            user_capacity: user_capacity
            execution_status: execution_status
            attributes:
              Power_On_Hours:
                flag: flag
                raw_value: raw_value
                worst: worst
                id: id
                type: type
                thresh: thresh
                updated: updated
                value: value
                when_failed: when_failed
              Reallocated_Sector_Ct:
                flag: flag
                raw_value: raw_value
                worst: worst
                id: id
                type: type
                thresh: thresh
                updated: updated
                value: value
                when_failed: when_failed
            sata_version: sata_version
            sector_size: sector_size
            smart_error_log: smart_error_log
            smartctl_version: smartctl_version
            overall_health: overall_health
            is_sas: true
          size: size
          vendor: HP
          description: description
          serial_number: CZ33109CHV
          id: disk
        - product: product
          smartctl:
            device_model: device_model
            ata_version: ata_version
            smart_support:
              available: true
              enabled: true
            serial_number: CZ33109CHV
            firmware_version: firmware_version
            rpm: rpm
            user_capacity: user_capacity
            execution_status: execution_status
            attributes:
              Power_On_Hours:
                flag: flag
                raw_value: raw_value
                worst: worst
                id: id
                type: type
                thresh: thresh
                updated: updated
                value: value
                when_failed: when_failed
              Reallocated_Sector_Ct:
                flag: flag
                raw_value: raw_value
                worst: worst
                id: id
                type: type
                thresh: thresh
                updated: updated
                value: value
                when_failed: when_failed
            sata_version: sata_version
            sector_size: sector_size
            smart_error_log: smart_error_log
            smartctl_version: smartctl_version
            overall_health: overall_health
            is_sas: true
          size: size
          vendor: HP
          description: description
          serial_number: CZ33109CHV
          id: disk
        cpu:
        - settings:
            enabledcores: enabledcores
            cores: cores
            threads: threads
          hz: hz
          capabilities:
            vmx: true
            x86-64: x86-64
            cpufreq: cpufreq
            ht: ht
          vendor: HP
          description: description
          serial_number: CZ33109CHV
          slot: slot
        - settings:
            enabledcores: enabledcores
            cores: cores
            threads: threads
          hz: hz
          capabilities:
            vmx: true
            x86-64: x86-64
            cpufreq: cpufreq
            ht: ht
          vendor: HP
          description: description
          serial_number: CZ33109CHV
          slot: slot
        chassis:
          product: product
          serial: CZ33109CHV
          vendor: HP
          motherboard:
            product: product
            serial: CZ33109CHV
            vendor: HP
          description: description
          firmware:
            date: 2000-01-23
            vendor: HP
            description: description
            version: J01
        network:
        - settings:
            broadcast: "yes"
            driver: driver
            port: port
            ip: ip
            latency: latency
            link: "yes"
            duplex: full
            driverversion: driverversion
            firmware: firmware
            autonegotiation: "on"
            multicast: "yes"
            speed: 1Gbit/s
          logical_name: logical_name
          product: product
          capabilities:
            ethernet: ethernet
            msi: msi
            pciexpress: pciexpress
            link_speeds:
              "1000bt-fd": 1000bt-fd
              "10bt": 10bt
              "100bt": 100bt
              "10bt-fd": 10bt-fd
              "100bt-fd": 100bt-fd
            msix: msix
            cap_list: cap_list
            bus_master: bus_master
            physical: physical
            tp: tp
            pm: pm
            autonegotiation: autonegotiation
          mac_address: 00:15:17:DB:63:01
          vendor: HP
          lldp:
            vlan:
              name: name
              id: id
              label: label
            port:
              description: description
              auto_negotiation:
                enabled: "yes"
                supported: "yes"
            chassis:
              mac_address: 00:15:17:DB:63:01
              name: name
              description: description
        - settings:
            broadcast: "yes"
            driver: driver
            port: port
            ip: ip
            latency: latency
            link: "yes"
            duplex: full
            driverversion: driverversion
            firmware: firmware
            autonegotiation: "on"
            multicast: "yes"
            speed: 1Gbit/s
          logical_name: logical_name
          product: product
          capabilities:
            ethernet: ethernet
            msi: msi
            pciexpress: pciexpress
            link_speeds:
              "1000bt-fd": 1000bt-fd
              "10bt": 10bt
              "100bt": 100bt
              "10bt-fd": 10bt-fd
              "100bt-fd": 100bt-fd
            msix: msix
            cap_list: cap_list
            bus_master: bus_master
            physical: physical
            tp: tp
            pm: pm
            autonegotiation: autonegotiation
          mac_address: 00:15:17:DB:63:01
          vendor: HP
          lldp:
            vlan:
              name: name
              id: id
              label: label
            port:
              description: description
              auto_negotiation:
                enabled: "yes"
                supported: "yes"
            chassis:
              mac_address: 00:15:17:DB:63:01
              name: name
              description: description
      properties:
        chassis:
          $ref: '#/components/schemas/chassis'
        cpu:
          items:
            $ref: '#/components/schemas/cpu'
          type: array
        disks:
          items:
            $ref: '#/components/schemas/disk'
          minItems: 1
          type: array
        ipmi:
          $ref: '#/components/schemas/ipmi'
        memory:
          items:
            $ref: '#/components/schemas/memoryBank'
          minItems: 1
          type: array
        network:
          items:
            $ref: '#/components/schemas/network'
          title: network
          type: array
      title: result
  securitySchemes:
    ApiKeyAuth:
      description: API key authentication by setting `X-LSW-Auth` header.
      in: header
      name: X-LSW-Auth
      type: apiKey
    BearerAuth:
      scheme: bearer
      type: http
